### ISSUE TITLE
Allow for 'dry running' commands

### ISSUE THREAD

**Issue by JimNero009** [Skyscanner/turbolift#38]
Before committing to a change (pun absolutely intended), it is sometimes useful to validate that the changes that were made actually came out sensibly in practise. 

I would like to see a configuration/environment option to commands like turbolift commit and turbolift create-prs (i.e. any write-like commands) to run them in a dry run mode. For example, the dry run commit could be a report of each git diff, and for create-prs it might be a summary of the git diff against the latest default branch.

**Comment by JimNero009** [comment]
I think I would prefer an 'end to end' dry run, rather than the step-by-step 'dry run and confirm' workflow of the previous version. This could be personal preference though, so perhaps we start there (the presence of some envar, off by default, that asks for confirmation when 'write' changes happen) and iterate upon that, re-using the functionality?

**Comment by rnorth** [comment]
Sure, I guess it's pretty doable to collate that and emit it at the end. I'd definitely suggest doing this as a flag (like `--dry-run`) rather than an env var, for ease of discovery. 

Maybe the thing that I was thinking of (and which the bash version did) would be better described as a `--review` mode. I get the distinction now!
