### ISSUE TITLE
Do not create forks if not necessary

### ISSUE THREAD

**Issue by arnaugm** [Skyscanner/turbolift#48]
Turbolift creates a fork for each project it needs to interact with.
Being Turbolift an excellent tool to handle maintenance tasks in the projects where you work usually it doesn't make much sense to fork these repositories where you already have write access.
It would be better if Turbolift could use the original repository if possible and fallback to a fork if not.

**Comment by Macavirus** [comment]
Hi, thank you for this excellent project!

I'd like to make a first attempt at this. First want to check with you if this approach is roughly correct:

1. Add a new function in `internal/github/github.go` called `Clone` that would use `execInstance` to run `gh repo clone`
2. Add tests for that function in `internal/github/github_test.go`
3. Update `cmd/clone/clone.go` to run the new `Clone` function instead of `ForkAndClone` around here: https://github.com/Skyscanner/turbolift/blob/cc4316ba4214f17c35b988aaa24ee35163b72d6a/cmd/clone/clone.go#L74

However, there is still some ambiguity in this issue that I'd like to confirm:
- Should the behaviour by default just clone instead of fork?
- Is there any expectation of backwards compatibility with current behaviour?
- Should we put the old behaviour behind a flag?

It seems like by default running a command that uses `gh pr create` later will by default do the right thing:
https://cli.github.com/manual/gh_pr_create

> Working with forks
> This command will automatically create a fork for you if you're in a repository that you don't have permission to push to.

So we don't necessarily need to check explicitly for write permissions.

**Comment by sledigabel** [comment]
Hi @Macavirus,

Thank you for your post,
Your proposal sounds great and certainly would address @arnaugm 's feature request,

For a long time our internal process relied on personal forks, I don't think any of us were aware of the gh pr create dark magic!

The approach sounds like a total win-win, Feel free to have a stab at it!

**Comment by rnorth** [comment]
Yep this sounds good to me - if we can avoid forking when it's unnecessary _and_ automatically fork when it is necessary, it is good.

> It seems like by default running a command that uses gh pr create later will by default do the right thing

For some reason I had no idea that this was the case! Perhaps I was working on outdated knowledge.

In terms of backwards compatibility expectations, I would say the only thing that matters is that the existing `turbolift clone ... commit ... create-prs` _works_ without changes (creates PRs). Nobody _wants_ unnecessary fork creation as a side-effect, so there's no need to preserve it.

I do think it would be good to keep the old behaviour behind a flag, i.e. `turbolift clone --fork` to make it always fork.

Thank you!

**Comment by arnaugm** [comment]
The idea sounds great to me as well. And I would also go for the option of only fork if necessary and provide the `--fork` flag to force it.

**Comment by lanwen** [comment]
Can report also that forking before cloning currently produces non-idempotent results:
- run `clone`
- fail to do something and `rm -rf work`
- run `clone` again
- fail on checkout as directory doesn't exist

as `gh` would report fork as a successful and wouldn't actually clone the fork. Simple clone would do a better job here

**Comment by sledigabel** [comment]
@lanwen That one i'm guessing is more because the `work` dir is created by init and is expected to be here for the clone to happen. A quick test is showing that if `work` exist the clone can happen again. I can file a quick issue to get this one fixed.

**Comment by sledigabel** [comment]
@lanwen in fact looking at this again the `work` dir should be recreated fine.
https://github.com/Skyscanner/turbolift/blob/main/cmd/clone/clone.go#L59

I've tried to delete it and it clones back fine into a work dir.

**Comment by lanwen** [comment]
@sledigabel That's interesting:
![image](https://user-images.githubusercontent.com/1964214/121048296-f6970600-c7b6-11eb-8bb0-ac8f565d3891.png)

**Comment by sledigabel** [comment]
OK, I just ran it again and I also get a warning but no error:
![image](https://user-images.githubusercontent.com/1921711/121051614-7d48e480-c7b1-11eb-89b4-7b3fb766dbcc.png)

the `gh` error is from the fact that the directory is created by `turbolift` and doesn't leave that responsibility to the clone so we can catch the error in case it cannot get created.

As for your error, this is very strange. Can you check the permissions on your work directory after the error? Did it clone successfully and failed at the checkout phase? Can you run `git` normally?

**Comment by lanwen** [comment]
@sledigabel all fine with permissions on the directory, it even created the org subdir within the `work`. If I directly execute `gh repo fork --clone=true <org>/<repo>` within the `work/<org>` it works fine, however turbolift execution leaves org dir empty.

**Comment by lanwen** [comment]
@sledigabel could it be because of some tricky forking inside of the `gh`? So that we wait only for `gh` but immediately after it checks an existance and start forking, we cancel that and continue to checkout? Anyway, direct clone helps in my case reliable and not sure worth of investigating further

**Comment by sledigabel** [comment]
Closing, added a `no-fork` feature with #62.
Making it transparent is still the long term goal (checking if you have the permissions to branch at clone time) but harder to implement at the moment.
